### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Solido** [pmlopes/openfaas-vertx-native-template#1]
Hello,

I've been testing this template and also quarkus but I can't build the image.
Seems like the image version is not up to date so I modified the Dockerfile to move to the last version but the build still fail later when trying to COPY the target.

Thank you !

**Comment by pmlopes** [comment]
The template has been updated. There are a couple of changes that are not backward compatible. The template is now using: https://github.com/pmlopes/vertx-lambda-runtime

This means that the same function can be used on `OpenFaaS`, `AWS Lambda` or `knative`.

The docker image is now using the latest stable `GraalVM 19.1.0`.

Finally a function looks like this:

```java
public class MyLambda implements Lambda<Buffer> {
  @Override
  public void handle(Message<Buffer> event) {
    System.out.println("HEADERS: " + event.headers());
    System.out.println("BODY: " + event.body());

    // Here your business logic...

    event.reply(new JsonObject().put("message", "Hello!"));
  }
}
```
